### ISSUE TITLE
Image paste error

### ISSUE THREAD

**Issue by beepboopbeep3000** [mankinence/ImageResizer#16]
Although the error message did not call out this plugin, after disabling the addon I no longer received the message when pasting an image on an existing card

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.38 (355e4cd5) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-21 08:59:59

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "aqt\editor.py", line 442, in onBridgeCmd
  File "aqt\editor.py", line 944, in onPaste
  File "aqt\editor.py", line 1062, in onPaste
  File "aqt\editor.py", line 1056, in _onPaste
  File "<decorator-gen-14>", line 2, in _processMime
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: _processMime_around() got multiple values for argument '_old'

**Comment by searene** [comment]
Have you tried updating this addon?

**Comment by beepboopbeep3000** [comment]
I close anki every few days or so and it auto updates the add-ons

**Comment by beepboopbeep3000** [comment]
Looks like there is an update available :/  
I'll give it another shot

**Comment by autoditactics** [comment]
I'm getting a somewhat similar error on MacOS when I drag text into the editor. (I couldn't copy and paste text for some reason.)
It says
> Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.14.2
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-27 11:03:43
관여된 것으로 추정되는 확장 프로그램:⁨ImageResizer⁩
Caught exception:
Traceback (most recent call last):
  File "aqt/editor.py", line 1061, in dropEvent
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-34>", line 2, in _processMime
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/suranchimeg2019/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 240, in _processMime_around
    logger.debug(mime.urls()[0].toString())
IndexError: list index out of range

**Comment by searene** [comment]
@autoditactics Can you update ImageResizer? It should be resolved after you update it.

**Comment by autoditactics** [comment]
@searene Yes, it's resolved for me. Thank you.
