### ISSUE TITLE
Error when pasting text

### ISSUE THREAD

**Issue by tirsoam** [mankinence/ImageResizer#18]
Hi, I just updated the add-on today. After updating, I tried to edit a note and it wouldn't let me use Cmd + V (the "paste" shortcut on Mac). An error window appears on the screen. It indicated that the add-on possibly involved in the error was ImageResizer, so I disabled it, restarted Anki and copy-pasting worked again just fine. To be clear, I never tried to copy or paste images or edit a note that had an image on it.

**Comment by searene** [comment]
Hi, could you show me the error message?

**Comment by tirsoam** [comment]
It says:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2021-03-27 12:29:36
Add-ons possibly involved: ⁨ImageResizer, Frozen Fields⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 35, in cmd
  File "aqt/webview.py", line 124, in _onCmd
  File "aqt/webview.py", line 569, in _onBridgeCmd
  File "<decorator-gen-10>", line 2, in onBridgeCmd
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/tirsoacuna/Library/Application Support/Anki2/addons21/516643804/main.py", line 135, in onBridge
    return _old(self, str)
  File "aqt/editor.py", line 443, in onBridgeCmd
  File "aqt/editor.py", line 945, in onPaste
  File "aqt/editor.py", line 1063, in onPaste
  File "aqt/editor.py", line 1057, in _onPaste
  File "<decorator-gen-4>", line 2, in _processMime
  File "anki/hooks.py", line 89, in decorator_wrapper
  File "anki/hooks.py", line 86, in repl
  File "/Users/tirsoacuna/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 256, in _processMime_around_with_extended
    return _processMime_around(self, mime, _old)
  File "/Users/tirsoacuna/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 240, in _processMime_around
    logger.debug(mime.urls()[0].toString())
IndexError: list index out of range

**Comment by searene** [comment]
Could you try updating this addon again? I just uploaded a new version.

**Comment by tirsoam** [comment]
Yes! I updated it and it works just fine now. Thank you so much!

**Comment by searene** [comment]
You are welcome :)
