### ISSUE TITLE
Error when pasting both image and text

### ISSUE THREAD

**Issue by rober-m** [mankinence/ImageResizer#19]
I updated the add-on a few minutes ago, and I can no longer paste anything. Both images and text generate the same error message:

```
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-27 13:40:56
Add-ons possibly involved: ⁨ImageResizer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 37, in cmd
  File "aqt/webview.py", line 123, in _onCmd
  File "aqt/webview.py", line 547, in _onBridgeCmd
  File "aqt/editor.py", line 416, in onBridgeCmd
  File "aqt/editor.py", line 928, in onPaste
  File "aqt/editor.py", line 1038, in onPaste
  File "aqt/editor.py", line 1032, in _onPaste
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-18>", line 2, in _processMime
  File "anki/hooks.py", line 638, in decorator_wrapper
  File "anki/hooks.py", line 635, in repl
  File "/Users/robertino/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 240, in _processMime_around
    logger.debug(mime.urls()[0].toString())
IndexError: list index out of range
```

**It worked fine until the update.** When I play around with the config, the error persists. The only way to stop the error is by unchecking the "**Resize on pasting**" option, but the **add-on stops working even when pressing the shortcut**. 

The issue seems to be different than #17

**Comment by rober-m** [comment]
Checked for updates again after seeing #18  and the last version resolved the issue for me too.

Thank you for your work!
