### ISSUE TITLE
Pasting problem

### ISSUE THREAD

**Issue by clean0129** [mankinence/ImageResizer#25]
This happens when i try to paste anything to the field.
Debug info:
Anki 2.1.40 (cf446733) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-06-10 00:02:07

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 35, in cmd
  File "aqt\webview.py", line 124, in _onCmd
  File "aqt\webview.py", line 569, in _onBridgeCmd
  File "<decorator-gen-88>", line 2, in onBridgeCmd
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
  File "C:\Users\hp\AppData\Roaming\Anki2\addons21\516643804\main.py", line 135, in onBridge
    return _old(self, str)
  File "aqt\editor.py", line 443, in onBridgeCmd
  File "aqt\editor.py", line 945, in onPaste
  File "aqt\editor.py", line 1063, in onPaste
  File "aqt\editor.py", line 1057, in _onPaste
  File "<decorator-gen-36>", line 2, in _processMime
  File "anki\hooks.py", line 89, in decorator_wrapper
  File "anki\hooks.py", line 86, in repl
TypeError: _processMime_around() got multiple values for argument '_old'

**Comment by searene** [comment]
That's weird. I'm using the exact same Anki version and OS as yours, but I'm not able to reproduce the problem. Could you try uninstalling this addon and installing it again?

**Comment by clean0129** [comment]
ok

**Comment by clean0129** [comment]
It works now. I'll contact you again if I get any more problems. THX
