### ISSUE TITLE
Settings UI incompatible with Qt6

### ISSUE THREAD

**Issue by darren-moore** [mankinence/ImageResizer#31]
Opening the settings in the qt6 version of Anki results in the following error.
This can be resolved by simply commenting out that line where QDesktopWidget is used. I'm not sure what the updated API for Qt6 is though, if we wanted to preserve the centering functionality.
```
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 6.3.0 PyQt 6.3.0
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-05 22:57:07

Caught exception:
Traceback (most recent call last):
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\1214357311\__init__.py", line 109, in _settings
    self.settingsMw = Settings(self, Setup.config)
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\1214357311\__init__.py", line 363, in __init__
    self.setupUI()
  File "C:\Users\username\AppData\Roaming\Anki2\addons21\1214357311\__init__.py", line 517, in setupUI
    self.move(QDesktopWidget().availableGeometry().center() - self.frameGeometry().center())
NameError: name 'QDesktopWidget' is not defined
```

**Comment by searene** [comment]
Hi,

Just let you know, I'm trying to make it work on PyQt6 these days, it shouldn't take long.

**Comment by searene** [comment]
Hi,

It's supported now, you can try updating the addon and see if it works.

**Comment by darren-moore** [comment]
Everything works after updating. Thank you!
