### ISSUE TITLE
Unable to update add-on config

### ISSUE THREAD

**Issue by JuliaIskra** [mankinence/ImageResizer#36]
When I'm trying to open config of the add-on I get the following error:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1.2-arm64-arm-64bit
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-02 21:32:35
Add-ons possibly involved: ⁨ImageResizer⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.addons", line 982, in onConfig
  File "/Users/julianemtseva/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 125, in _settings
    self.settingsMw = Settings(self, Setup.config)
  File "/Users/julianemtseva/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 379, in __init__
    self.setupUI()
  File "/Users/julianemtseva/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 516, in setupUI
    mainLayout.addWidget(self.hLine())
  File "/Users/julianemtseva/Library/Application Support/Anki2/addons21/1214357311/__init__.py", line 570, in hLine
    line.setFrameShape(QFrame.HLine)
AttributeError: type object 'QFrame' has no attribute 'HLine'
```

**Comment by searene** [comment]
Fixed, could you update the addon and try again?

**Comment by JuliaIskra** [comment]
now it works, thank you for the fast fix!
